### ISSUE TITLE
Default export missing in type declaration

### ISSUE THREAD

**Issue by joshuajaco** [jefflau/jest-fetch-mock#146]
When trying to call a function on the default export you get the following type error: 
`TS2339: Property 'enableMocks' does not exist on type 'typeof import("/Users/joshua.jacobowitz/workspace/injixo-ui/node_modules/jest-fetch-mock/types/index")'.`
This is because the typings file is missing a default export declaration.

**Comment by yinzara** [comment]
That sounds like you did:
```
import fetchMock from "jest-fetch-mock"

fetchMock.enableMocks()
```

Instead it should be:

```
import from "jest-fetch-mock"

fetch.enableMocks()
```

**Comment by joshuajaco** [comment]
Works with v3.0.2
