### ISSUE TITLE
Test Failure After Upgrading to CRA 4.0

### ISSUE THREAD

**Issue by Bangertm** [jefflau/jest-fetch-mock#184]
After upgrading react-scripts to 4.0, I'm seeing an issue jest-fetch-mock in tests that previously passed. In particular calling `fech` is raising: 
```console
TypeError: isMocking is not a function or its return value is not iterable
```
from this line: 
https://github.com/jefflau/jest-fetch-mock/blob/6c1f4bc78c12eda4437f4c761a934a72a3648e02/src/index.js#L100

react-scripts 4.0 [introduces ](https://github.com/facebook/create-react-app/blob/master/CHANGELOG.md#jest)Jest 26 and a default of setting `resetMocks` to `true`. I have found that setting `resetMocks` to `false` will fix the issue. Ideally I would be able to leave `resetMocks` in its default.

**Comment by yinzara** [comment]
Unfortunately jest's automatic "resetMocks" functionality completely breaks how jest-fetch-mock works.

To fix, you either can disable resetMocks as you suggested or call "fetchMock.resetMocks()" in a "beforeEach()".

We'll have to add some additional documentation about this.

**Comment by gerhardsletten** [comment]
Also looks like you need to add `fetch.dontMock` in the beforeEach (if you only want to override moch some fetches):
```
beforeEach(async function () {
  fetch.resetMocks()
  fetch.dontMock()
})
```
even if you have it in the global setupFiles for jest
```
require('jest-fetch-mock').enableMocks()
fetch.dontMock()
```

**Comment by dreamerchandra** [comment]
In CRA 4.0.1 this issue is happening... Update the doc on how to resolve this... 
I can't find a way-around... Solutions discussed here aren't working with `fetch. mockResponseOnce`. However `fetch.mockResolvedValueOnce` seems to work

So I'm currently using like this `fetch.mockResolvedValueOnce({ json: () => ({ data: 'res' }) })`

**Comment by ericchernuka** [comment]
Just following up on this to see if anyone was able to resolve this easily? I'm hitting this pretty hard right now.

**Comment by zigasinko** [comment]
There must be something else wrong with using _jest-fetch-mock_ in _create-react-app_ >4.0 (probably an issue with Jest 26 which was updated in latest version of _create-react-app_. For me everything fetch related comes back undefined. Except if I put in `fetchMock.dontMock();` which means fallback to default fetch API and that's not a solution.

**Comment by MarkusRohlof** [comment]
For anyone else who might have been confused for the better part of an hour about how to set `resetMocks` to `false` with a `create-react-app` project, just add a `"jest"` section to your `package.json`:

```json
"jest": {
  "resetMocks": false
}
```

**Comment by yinzara** [comment]
> Just following up on this to see if anyone was able to resolve this easily? I'm hitting this pretty hard right now.

Have you tried setting the "resetMocks" to false in the Jest config like suggested?

**Comment by yinzara** [comment]
I'm going to close this issue as I've now updated the README.md with instructions on setting this Jest configuration and why it happened.

**Comment by ilivestrong** [comment]
thank you so much! After 2 hours of Googling, found this thread. <3
